# Generated by Django 6.0 on 2026-01-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailyreport_site_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='material_status',
            field=models.CharField(choices=[('SUFFICIENT', 'Sufficient (100%)'), ('LOW', 'Running Low (50%)'), ('CRITICAL', 'Critical Shortage (10%)')], default='SUFFICIENT', max_length=20),
        ),
    ]
