# Generated by Django 6.0 on 2026-01-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_material_dailyreport_material_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='cost_today',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
