# Generated by Django 6.0 on 2026-03-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dailyreport_cost_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='risk_level',
            field=models.CharField(default='Assessed', max_length=20),
        ),
    ]
