# Generated by Django 6.0.4 on 2026-04-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dailyreport_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SITE_ENGINEER', 'Site Engineer'), ('CLIENT', 'Client')], default='ADMIN', max_length=20),
        ),
    ]
