# Generated by Django 6.0.4 on 2026-04-10 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
