# Generated by Django 6.0.4 on 2026-04-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_status_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='material_status',
            field=models.CharField(default='SUFFICIENT', max_length=20),
        ),
    ]
