# Generated by Django 6.0.4 on 2026-04-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_dailyreport_material_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status_updated_at',
        ),
        migrations.AddField(
            model_name='project',
            name='last_action_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
